[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer-runs = 200
via_ir = true
optimize_yul = true
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
[rpc_endpoints]
baseSepolia = "https://base-sepolia.g.alchemy.com/v2/c9luSIn-9uUW-b79ay_Pf6pVf8rlc3i3" 


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
